--Aubrey Annas
SELECT FISCAL_MONTH_ID
		,COUNT(*) AS BUS_DAYS
FROM WISDM.DIM.DATE
WHERE DATE_ID <= CAST(GETDATE() AS DATE)
		AND FISCAL_YEAR_ID = '2019'
		AND DAY_OF_WEEK BETWEEN 2 AND 6
		AND COMPANY_HOLIDAY IS NULL
GROUP BY FISCAL_MONTH_ID
ORDER BY FISCAL_MONTH_ID