USE RegMTW;

IF OBJECT_ID('TEMPDB..#LSCFlash') IS NOT NULL
DROP TABLE #LSCFlash

SELECT L.[DATE] AS [DATE]
		,CONVERT(VARCHAR(20),'Web Leads') AS [CATEGORY]
		,SUM(CASE WHEN L.[channel] = 'WEB'
					THEN L.[WEBLeads] END) AS [COUNT]
INTO #LSCFlash
FROM [RptCB].[Rpt].[t_WSTWEBLeadssummary] AS L
WHERE L.[fiscal_month_end] = '07-21-2019'
GROUP BY L.[date]
ORDER BY L.[date]

INSERT INTO #LSCFlash
SELECT L.[DATE] AS [DATE]
		,CONVERT(VARCHAR(20),'Chat Leads') AS [CATEGORY]
		,SUM(CASE WHEN L.[channel] = 'CHAT'
					THEN L.[WEBLeads] END) AS [COUNT]
FROM [RptCB].[Rpt].[t_WSTWEBLeadssummary] AS L
WHERE L.[fiscal_month_end] = '07-21-2019'
GROUP BY L.[date]
ORDER BY L.[date]

INSERT INTO #LSCFlash
SELECT S.[SALE_DATE] AS [DATE]
		,CONVERT(VARCHAR(20),'BSR Data') AS [CATEGORY]
		,ISNULL(SUM(CASE WHEN S.[CHANNEL] = 'INBOUND'
					THEN S.[DATA_SALES] END),0) AS [COUNT]
FROM [RptCB].[Ext].[v_WSTRtbBigPictureSalesDaily] AS S
WHERE S.[FISCAL_MONTH_END] = '07-21-2019'
GROUP BY S.[SALE_DATE]
ORDER BY S.[SALE_DATE]

INSERT INTO #LSCFlash
SELECT S.[SALE_DATE] AS [DATE]
		,CONVERT(VARCHAR(20),'Core Data') AS [CATEGORY]
		,ISNULL(SUM(CASE WHEN S.[CHANNEL] = 'OBSR CORE'
					THEN S.[DATA_SALES] END),0) AS [COUNT]
FROM [RptCB].[Ext].[v_WSTRtbBigPictureSalesDaily] AS S
WHERE S.[FISCAL_MONTH_END] = '07-21-2019'
GROUP BY S.[SALE_DATE]
ORDER BY S.[SALE_DATE]

INSERT INTO #LSCFlash
SELECT S.[SALE_DATE] AS [DATE]
		,CONVERT(VARCHAR(20),'Web Data') AS [CATEGORY]
		,ISNULL(SUM(CASE WHEN S.[CHANNEL] = 'WEB'
					THEN S.[DATA_SALES] END),0) AS [COUNT]
FROM [RptCB].[Ext].[v_WSTRtbBigPictureSalesDaily] AS S
WHERE S.[FISCAL_MONTH_END] = '07-21-2019'
GROUP BY S.[SALE_DATE]
ORDER BY S.[SALE_DATE]

INSERT INTO #LSCFlash
SELECT S.[SALE_DATE] AS [DATE]
		,CONVERT(VARCHAR(20),'Chat Data') AS [CATEGORY]
		,ISNULL(SUM(CASE WHEN S.[CHANNEL] = 'CHAT'
					THEN S.[DATA_SALES] END),0) AS [COUNT]
FROM [RptCB].[Ext].[v_WSTRtbBigPictureSalesDaily] AS S
WHERE S.[FISCAL_MONTH_END] = '07-21-2019'
GROUP BY S.[SALE_DATE]
ORDER BY S.[SALE_DATE]

INSERT INTO #LSCFlash
SELECT S.[SALE_DATE] AS [DATE]
		,CONVERT(VARCHAR(20),'CAM Data') AS [CATEGORY]
		,ISNULL(SUM(CASE WHEN S.[CHANNEL] IN ('INBOUND CAM','OUTBOUND CAM')
					THEN S.[DATA_SALES] END),0) AS [COUNT]
FROM [RptCB].[Ext].[v_WSTRtbBigPictureSalesDaily] AS S
WHERE S.[FISCAL_MONTH_END] = '07-21-2019'
GROUP BY S.[SALE_DATE]
ORDER BY S.[SALE_DATE]

INSERT INTO #LSCFlash
SELECT C.[CALL_DATE] AS [DATE]
		,CONVERT(VARCHAR(20),'BSR Calls') AS [CATEGORY]
		,SUM(C.[CALLS_HANDLED]) AS [COUNT]
FROM [RptCB].[Ext].[v_WSTRtbBigPictureCallsDaily] AS C
WHERE C.[FISCAL_MONTH_END] = '07-21-2019'
	AND C.[CHANNEL] = 'INBOUND'
GROUP BY C.[CALL_DATE]
ORDER BY C.[CALL_DATE]

SELECT [DATE]
		,[CATEGORY]
		,[COUNT]
FROM #LSCFlash
ORDER BY [DATE]
